apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
  labels:
    cloud.googleapis.com/location: asia-northeast1
    run.googleapis.com/startupProbeType: Default
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: SERVICE_ACCOUNT_NAME
      containers:
        - image: IMAGE_PATH
          ports:
            - name: http1
              containerPort: 8000
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
            successThreshold: 1

  traffic:
    - percent: 100
      latestRevision: true
