# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks: 
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
        - id: check-json
        - id: check-toml
        - id: detect-private-key
        - id: pretty-format-json
          args: [--autofix]

  -   repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.3.1
      hooks:
        # Run the linter.
        - id: ruff
          args: [ --fix ]
        # Run the formatter.
        - id: ruff-format

#   -   repo: local
#       hooks:
#         -   id: pytest
#             name: Run pytest
#             entry: cd llm-server && rye run python -m pytest .
#             language: system
#             types: [python]
